window.JOB_DASHBOARD = {
  "generatedAt": "2026-09-23T20:30:00.000Z",
  "boardsScannedAt": "2026-09-23T20:30:00.000Z",
  "linkedinScannedAt": "2026-09-23T20:30:00.000Z",
  "maxAgeDays": 21,
  "jobs": [
    {
      "id": "1komma5 | senior product designer heartbeat ai",
      "fingerprint": "1komma5 | senior product designer heartbeat ai",
      "title": "Senior Product Designer – Heartbeat AI (m/f/d)",
      "company": "1Komma5°",
      "companyAbout": "Climate-tech company for home energy — heat pumps, solar, and storage — building Heartbeat AI energy management for households.",
      "bucket": "A",
      "source": "ClimateTechList",
      "score": 91,
      "band": "strong",
      "postedAt": "2026-08-25T00:00:00.000Z",
      "location": "Remote within Germany (Hamburg / Berlin / Munich offices)",
      "workModel": "remote",
      "salary": "est. €70–85k",
      "postingUrl": "https://1komma5grad.com/careers",
      "boardUrl": "https://www.climatetechlist.com/jobs?search=Design&location=Europe",
      "directApplyUrl": "https://1komma5grad.com/careers",
      "linkedinUrl": "",
      "summary": "Already-engaged company — cover letter exists. Confirm status before re-applying.",
      "whyFit": "Greentech mission + IC product design; remote DE fits bucket A.",
      "gaps": "Confirm this is the same role you already wrote to.",
      "talkingPoints": [
        "Lead with energy-transition product work",
        "Confirm whether Heartbeat AI posting is still open"
      ]
    },
    {
      "id": "elearnio | senior product designer ux/ui",
      "fingerprint": "elearnio | senior product designer ux/ui",
      "title": "Senior Product Designer (UX/UI)",
      "company": "elearnio",
      "companyAbout": "Education / corporate L&D SaaS — onboarding and learning platform used across many languages.",
      "bucket": "A",
      "source": "DesignJobs.World",
      "score": 81,
      "band": "strong",
      "postedAt": "2026-09-21T00:00:00.000Z",
      "location": "EU remote (Potsdam-based company)",
      "workModel": "remote",
      "salary": "est. €65–75k",
      "postingUrl": "https://designjobs.world/jobs/remote/senior-ui-ux-designer-elearnio-germany-77069",
      "boardUrl": "https://designjobs.world/jobs/remote/senior-ui-ux-designer-elearnio-germany-77069",
      "directApplyUrl": "https://join.com/companies/elearnio",
      "linkedinUrl": "",
      "summary": "Sole designer owning the platform, design system, and design QA; customer interviews; 15 languages; WCAG 2.1 AA.",
      "whyFit": "Design-systems ownership and multi-language product work map directly; German C1 for interviews.",
      "gaps": "They want logic-heavy B2B/SaaS and rule out brand-led portfolios — lead with product cases.",
      "talkingPoints": [
        "Being the whole design function",
        "Making a dense admin tool feel calm",
        "Designing for strings that change length across 15 locales"
      ]
    },
    {
      "id": "sidekick health | senior product designer ux&ui",
      "fingerprint": "sidekick health | senior product designer ux&ui",
      "title": "Senior Product Designer UX&UI (m/w/d)",
      "company": "Sidekick Health",
      "companyAbout": "Digital therapeutics — personalised treatment programmes for chronic disease (web and mobile).",
      "bucket": "A",
      "source": "LinkedIn",
      "score": 81,
      "band": "strong",
      "postedAt": "2026-09-20T00:00:00.000Z",
      "location": "Germany remote-friendly · Hamburg office",
      "workModel": "remote",
      "salary": "est. €65–85k",
      "postingUrl": "https://sidekickhealth.jobs.personio.com/job/563330",
      "boardUrl": "",
      "directApplyUrl": "https://sidekickhealth.jobs.personio.com/job/563330",
      "linkedinUrl": "https://www.linkedin.com/jobs/search/?keywords=Sidekick%20Health%20Senior%20Product%20Designer",
      "summary": "End-to-end web and mobile under regulatory constraints; German + English C1 required.",
      "whyFit": "Regulated-domain experience (Verimi); health app you designed and shipped; German research.",
      "gaps": "Confirm work model — some aggregators say hybrid Hamburg.",
      "talkingPoints": [
        "Designing inside regulatory constraints",
        "Shipping a health app solo",
        "Running research in German"
      ]
    },
    {
      "id": "up42 | product designer",
      "fingerprint": "up42 | product designer",
      "title": "Product Designer (m/f/x)",
      "company": "UP42",
      "companyAbout": "Earth-observation platform aggregating satellite imagery for vegetation, infrastructure, and disaster response.",
      "bucket": "B",
      "source": "LinkedIn",
      "score": 72,
      "band": "worth a look",
      "postedAt": "2026-09-22T00:00:00.000Z",
      "location": "Berlin hybrid (flexible Kreuzberg policy)",
      "workModel": "hybrid",
      "salary": "est. €70–80k",
      "postingUrl": "https://up42gmbh.recruitee.com/",
      "boardUrl": "",
      "directApplyUrl": "https://up42gmbh.recruitee.com/",
      "linkedinUrl": "https://www.linkedin.com/jobs/search/?keywords=UP42%20Product%20Designer",
      "summary": "Own a product area with complex data-rich interfaces and design-system contribution.",
      "whyFit": "Complex UX / data interfaces; design-system work; English-default team.",
      "gaps": "Title lacks Senior — check level early; hybrid rather than remote.",
      "talkingPoints": [
        "Making complex data legible",
        "Owning a product area end-to-end",
        "Climate-adjacent mission"
      ]
    },
    {
      "id": "vilgain | senior product designer consumer mobile",
      "fingerprint": "vilgain | senior product designer consumer mobile",
      "title": "Senior Product Designer — Consumer Mobile & Commerce",
      "company": "Vilgain",
      "companyAbout": "European nutrition food brand (500+ people, 11 countries) with DTC ecommerce and own labels.",
      "bucket": "A",
      "source": "DesignJobs.World",
      "score": 70,
      "band": "worth a look",
      "postedAt": "2026-09-17T00:00:00.000Z",
      "location": "EU remote (verify — careers page may say Praha / self-employed)",
      "workModel": "remote",
      "salary": "unstated",
      "postingUrl": "https://designjobs.world/jobs/remote/senior-product-designer-mobile-vilgain-europe-76843",
      "boardUrl": "https://designjobs.world/jobs/remote/senior-product-designer-mobile-vilgain-europe-76843",
      "directApplyUrl": "https://vilgain.com/career",
      "linkedinUrl": "",
      "summary": "Own new mobile app end-to-end plus e-shop; works with PM and CEO; expects Figma MCP and Claude.",
      "whyFit": "Your nutrition app shipped to App Store; conversion uplift experience; AI-assisted workflow match.",
      "gaps": "Conflicting remote vs Praha / self-employed signals — clarify before investing.",
      "talkingPoints": [
        "Shipping a consumer mobile app solo",
        "Conversion uplift that held for a year",
        "Using Claude and Figma MCP in production design"
      ]
    }
  ]
};
